# name: base
channels:
  - conda-forge
  - anaconda
  # - hcc
dependencies:
  # - beakerx
  - pip
  - python=3.8
  - jupyter
  - jupyterlab=2.2.0
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - cudatoolkit
  - jupyterlab_widgets
  - ipyfilechooser
  - constructor
    # - jupyterlab-extensions
  - nodejs
  - tensorflow
  # - cuda-driver
  - pip:
    - tensorflow-gpu==1.15.0
    - jupyterlab-git
  #   - -r file:requirements.txt
# jupyterlab_play_cell_button
# jlab-enhanced-cell-toolbar
# imjoy-jupyter-extension
